### PR TITLE
Create updated  Contact page 

### PR DESCRIPTION
**Pull request by rko0211**
I have created a simple and beautiful contact page for you. For that i have updated your HTML code and created a new CSS code file (Name :- **contact.css**)  to differentiate between your code and mine.

I make it responsive and beautiful. You can go through the link : [https://rko0211.github.io/APS-PUBLIC-SCHOOL/](https://rko0211.github.io/APS-PUBLIC-SCHOOL/)
, you can check Contact page from there. So, kindly review my PR and merge it under **Hacktoberfest 2023**. Thank You...

Fixes :-  #5

#hacktoberfest 2023 #hacktoberfest-accepted

### CODE REVIEW

**Comment by abhaytron** [comment]
Chage the background color to yellow as main page have, then I'll accept your PR.

**Comment by rko0211** [comment]
> Chage the background color to yellow as main page have, then I'll accept your PR.

I have done your requirement, now it is ready for merging. Thank You...

**Comment by rko0211** [comment]
Hey Please add **hacktoberfest-accepted**  and **hacktoberfest** level in this PR. So that they count it as valid PR. Thank you..

**Comment by abhaypratapsinghin** [comment]
hacktoberfest hacktoberfest-accepted

**Comment by rko0211** [comment]
Thank You very much

**Pull request merged**
